"""message

Revision ID: 6ba3c0487010
Revises: 2d2566c8bcfd
Create Date: 2024-06-30 17:35:38.088210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba3c0487010'
down_revision = '2d2566c8bcfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
