"""message

Revision ID: abb839a0c286
Revises: 6c73f3847884
Create Date: 2024-07-19 17:23:05.403676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb839a0c286'
down_revision = '6c73f3847884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
