"""message

Revision ID: b8ab37ffb2ca
Revises: de54ffb15725
Create Date: 2024-07-19 17:33:52.041007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ab37ffb2ca'
down_revision = 'de54ffb15725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
